### ISSUE TITLE
feat: add socials endpoint

### ISSUE THREAD

**Issue by xafn** [revanced/revanced-releases-api#30]
Allows us to easily change our social links when needed and reduces our connection. :dev_happy_emoji:

**Comment by alexandreteles** [comment]
Accepted. Should be available on the next feature package.

**Comment by alexandreteles** [comment]
I've started working on this :)

**Comment by alexandreteles** [comment]
This is done, the new feature pack will be integrated into `dev` and a new release is expected to drop today or tomorrow.

**Comment by alexandreteles** [comment]
Will be released with the merge of #53
