### ISSUE TITLE
feat: remove repository `TeamVanced/VancedMicroG` from configuration

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-releases-api#68]
**Describe the bug**

The API offers `TeamVanced/VancedMicroG`. 
RE: https://github.com/revanced/revanced-manager/pull/642#issuecomment-1382834783.

**Expected behavior**

The API should be agnostic to patches, but "Vanced Microg" is a dependency of a patch and the API offers it.

**Solution**

Remove the repository `TeamVanced/VancedMicroG` from [config.toml](https://github.com/revanced/revanced-releases-api/blob/main/config.toml):

```diff
[app]
- repositories = ["TeamVanced/VancedMicroG", "revanced/revanced-patcher", "revanced/revanced-patches", "revanced/revanced-integrations", "revanced/revanced-manager", "revanced/revanced-cli", "revanced/revanced-website", "revanced/revanced-releases-api"]
+ repositories = ["revanced/revanced-patcher", "revanced/revanced-patches", "revanced/revanced-integrations", "revanced/revanced-manager", "revanced/revanced-cli", "revanced/revanced-website", "revanced/revanced-releases-api"]
```

**Comment by alexandreteles** [comment]
Will be changed in the next feature pack.
