### ISSUE TITLE
feat: Migrate to the domain `revanced.app`

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-releases-api#9]
## **Is your feature request related to a problem? Please describe.**

Currently the API uses an arbitrary domain not "officially" backed by the ReVanced entity.

## **Describe the solution you'd like**

Migrate to the domain `revanced.api`.

## **Describe alternatives you've considered**

The `revanced.app` domain could resolve to a reverse proxy to the current domain.

**Comment by alexandreteles** [comment]
The API doesn't care about which domain is in front of it, so this should be fine. I would like to finish the current milestones and testing before we move it to the `revanced.app`.

I'll have to note down the CF settings relevant to the API so we can make sure that everything works fine during migration.

Additionally I could transfer `rvcd.win` to the team leader and we can keep this domain up and use it for all the infrastructure-related tasks so if the main domain falls to an attack or something the APIs are still up and working.

**Comment by alexandreteles** [comment]
Fixed.
