### ISSUE TITLE
feat: prereleases support

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-releases-api#94]
**Is your feature request related to a problem? Please describe.**
No way of getting pre-releases

**Describe the solution you'd like**
Add pre-releases

**Describe alternatives you've considered**
Provide pre-releases

**Additional context**
Need pre-releases

**Comment by Ushie** [comment]
I can PR this, @alexandreteles can you tell me if you're fine with my PRing the following?:

```diff
 {
   "tools": [
     {
       "repository": "string",
       "version": "string",
       "timestamp": "string",
       "name": "string",
       "size": "string",
       "browser_download_url": "string",
+      "browser_prerelease_download_url": "string",
       "content_type": "string"
     }
   ]
 }
 ```
 
 or is there a specific way you'd like to do it

**Comment by alexandreteles** [comment]
@Ushie Sorry for not getting back to you sooner. You're proposing that the API return the last pre-release version on `/tools`, correct? If so, I'm completely fine with it. Remember that this will likely double the time the endpoint requires to generate data the first time it is called after cache expiration, but it should still be acceptable. Please send the PR and add me to it.

**Comment by oSumAtrIX** [comment]
/tool/toolA
/tool/toolB 

And so on would solve the issue

**Comment by alexandreteles** [comment]
> /tool/toolA /tool/toolB
> 
> And so on would solve the issue

There are no current provisions for that, but that could be done.

**Comment by Indranil012** [comment]
isn't #93 relevent for this issue?

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/static-api This might supersede the entire repository

**Comment by alexandreteles** [comment]
> isn't #93 relevent for this issue?

Yes, but the development of the rewrite is stalled as we are testing a new implementation. This is why this issue is still open.
